### ISSUE TITLE
Provide full prepared query text in response and error object

### ISSUE THREAD

**Issue by mayurbangar** [vertica/vertica-nodejs#143]
When we get response back from the db 

`client.connect(query, params, (err, res) => {
     if(err) //This should have a field query which will give us the final prepared query that has caused error
})`

This will be very helpful to debug and to point out whether the issue is with syntax of query or parametrisation or anything else.

**Comment by h-serizawa** [comment]
The backend protocol doesn't return the failed prepared statement with the parameter values.

[Error when one parameter was missed]
```
error: Incorrect number of parameters for prepared statement user by age and like name
    at Parser.parseErrorMessage (/mnt/c/work/git_repo/vertica-nodejs/packages/v-protocol/dist/parser.js:365:106)
    at Parser.handlePacket (/mnt/c/work/git_repo/vertica-nodejs/packages/v-protocol/dist/parser.js:141:29)
    at Parser.parse (/mnt/c/work/git_repo/vertica-nodejs/packages/v-protocol/dist/parser.js:56:38)
    at Socket.<anonymous> (/mnt/c/work/git_repo/vertica-nodejs/packages/v-protocol/dist/index.js:30:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23) {
  length: 225,
  severity: 'ERROR',
  code: '26000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: '/data/jenkins/workspace/RE-ReleaseBuilds/RE-Nibbler/server/vertica/Session/ClientSession.cpp',
  line: '3774',
  routine: 'exec_bind_message'
}
```

[Syntax error]
```
error: Syntax error at or near "person"
    at Parser.parseErrorMessage (/mnt/c/work/git_repo/vertica-nodejs/packages/v-protocol/dist/parser.js:365:106)
    at Parser.handlePacket (/mnt/c/work/git_repo/vertica-nodejs/packages/v-protocol/dist/parser.js:141:29)
    at Parser.parse (/mnt/c/work/git_repo/vertica-nodejs/packages/v-protocol/dist/parser.js:56:38)
    at Socket.<anonymous> (/mnt/c/work/git_repo/vertica-nodejs/packages/v-protocol/dist/index.js:30:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23) {
  length: 165,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '19',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: '/data/jenkins/workspace/RE-ReleaseBuilds/RE-Nibbler/server/vertica/Parser/scan.l',
  line: '1056',
  routine: 'base_yyerror'
}
```
